name: test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'data/**'
      - 'site'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'data/**'
      - 'site'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Do session
      uses: mobiledevops/secret-to-file-action@v1
      with:
        base64-encoded-secret: ${{ secrets.SESSION }}
        filename: "session.json"
        is-executable: false
        working-directory: "data"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
          pip install pytest pytest-cov
          pytest --cov=eventminer --cov-report=xml --cov-report=html
      env:
        INSTAGRAM_USERNAME: ${{ secrets.USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.PASSWORD }}
        PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
        PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
        PROXY_COUNTRY: ${{ secrets.PROXY_COUNTRY }}
        PROXY_HOST_PORT: ${{ secrets.PROXY_HOST_PORT }}
